### ISSUE TITLE
Softmax gradient

### ISSUE THREAD

**Issue by Kurama622** [Apiquet/DeepLearningFrameworkFromScratchCpp#1]
Why is only the first part of the softmax gradient function code provided here, when it actually has two parts?

```cpp
void Softmax::backward(Eigen::MatrixXf &ddout, const Eigen::MatrixXf &dout) {
  ddout =
      dout.array() * (mForwardInputWithSoftmaxApplied.array() *
                      (1.f -
                     mForwardInputWithSoftmaxApplied.array()).array())
                         .array();
```

![image](https://github.com/Apiquet/DeepLearningFrameworkFromScratchCpp/assets/41457394/496e8cf0-1e76-488b-8967-4b68c40427a7)

**Comment by Apiquet** [comment]
Thank you for your question. Do the indexes i and j refer to the width and height dimensions? In my case, I only produce one value, so width=height=1, which leads to i=j in the backpass for each sample.
If you want to use this code to predict 2D maps then I think that an update must indeed be made for the case i!=j.
Please feel free to bring the update to the repository, it will be much appreciated.

**Comment by Kurama622** [comment]
I have simply implemented the backward function for softmax based on the formula. [#2](https://github.com/Apiquet/DeepLearningFrameworkFromScratchCpp/pull/2/files)
